---
title: "ARTS Metrics"
format: html
author: "Heidi Rodenhizer"
---

# Set-Up

```{r}
library(sf)
library(labelled)
library(viridis)
library(tidyverse)
```

```{r}
theme_set(theme_bw())
```

# Load Data

```{r}
arts = st_read(
  "../ARTS/ARTS_main_dataset/v.6.0.0/ARTS_main_dataset_v.6.0.0.geojson"
) |>
  st_make_valid()
tk_landscapes = st_read(
  "../rts_rep_analysis/input_data/OlefeldtThermokarstMap/data/Circumpolar_Thermokarst_Landscapes_epsg3413.shp"
) |>
  st_make_valid() |>
  mutate(
    across(
      TKWP:TKHP,
      ~ factor(
        .x,
        levels = c("None", "Low", "Moderate", "High", "Very High"),
        ordered = TRUE
      )
    )
  ) # TKWP = Wetland Thermokarst, TKThLP = Thermokarst Lakes, TKHP = Hillslope Thermokarst

tem_grid = st_read(
  "./data/aoi_5km_buffer_4km_rez_6931_pixel_polygons/aoi_5km_buffer_4km_rez_6931_pixel_polygons.shp"
)
```

```{r}
world = rnaturalearth::ne_countries(scale = "large", returnclass = "sf")
world = world |>
  st_transform(3413) |>
  st_crop(st_bbox(st_buffer(tk_landscapes, dist = 500000)))
```

# Area Distribution

```{r}
arts_filter = arts |>
  separate(
    BaseMapDate,
    into = c("BaseMapDateStart", "BaseMapDateEnd"),
    sep = ",",
    remove = FALSE
  ) |>
  mutate(
    across(
      c(BaseMapDateStart, BaseMapDateEnd),
      ~ as.Date(.x)
    )
  ) |>
  filter(
    TrainClass == "Positive" &
      LabelType == "Polygon" &
      BaseMapDateEnd == max(BaseMapDateEnd),
    .by = c(UID)
  )

arts_filter = arts_filter |>
  mutate(
    Area = as.numeric(st_area(arts_filter))
  ) |>
  set_variable_labels(Area = "Area (m^2)")
```

```{r}
(area_hist = ggplot(
  arts_filter,
  aes(x = Area)
) +
  geom_histogram(
    aes(y = ..count.. / sum(..count..)),
    color = "gray35",
    linewidth = 1,
    binwidth = 10000,
    boundary = 0
  ) +
  # geom_histogram(
  #   binwidth = 10000,
  #   boundary = 0
  # ) +
  scale_x_continuous(name = expression("RTS Area (m"^2 ~ ")")) +
  scale_y_continuous(
    name = "Proportion",
    expand = expansion(mult = c(0, 0.05))
  ))

# ggsave(
#   "./figures/rts_area.jpg",
#   area_hist,
#   height = 3,
#   width = 4
# )

area_bin_data = ggplot_build(area_hist)$data[[1]]
area_bin_data = area_bin_data |>
  select(area_min = xmin, area_max = xmax, count)
# write_csv(
#   area_bin_data,
#   "./data/area_bin_data.csv"
# )
```

# Thermokarst Landscapes Distribution

```{r}
tk_simplified = tk_landscapes |>
  group_by(TKWP, TKThLP, TKHP) %>%
  summarize(geometry = st_union(geometry)) |>
  st_make_valid() |>
  mutate(
    area_tk = as.numeric(st_area(geometry)) / 1e6,
    .before = geometry
  )
```

```{r}
ggplot() +
  geom_sf(data = world) +
  geom_sf(data = tk_simplified, aes(color = TKHP, fill = TKHP)) +
  scale_color_viridis(discrete = TRUE) +
  scale_fill_viridis(discrete = TRUE) +
  coord_sf(expand = FALSE)
```

```{r}
# arts_tk = arts_filter |>
#   st_join(
#     tk_simplified,
#     largest = TRUE
#   )

# st_write(
#   arts_tk,
#   "./data/arts_tk.geojson"
# )
arts_tk = st_read("./data/arts_tk.geojson")
```

```{r}
(rts_no_tk = ggplot() +
  geom_sf(data = world) +
  geom_sf(
    data = arts_tk |>
      filter(
        (TKWP == "None" | str_length(TKWP) == 0) &
          (TKThLP == "None" | str_length(TKWP) == 0) &
          (TKHP == "None" | str_length(TKWP) == 0)
      ),
    aes(
      color = "RTS With No\nThermokarst Likelihood",
      fill = "RTS With No\nThermokarst Likelihood"
    ),
    linewidth = 1,
  ) +
  scale_color_manual(
    name = "",
    values = c("RTS With No\nThermokarst Likelihood" = "darkred")
  ) +
  scale_fill_manual(
    name = "",
    values = c("RTS With No\nThermokarst Likelihood" = "darkred")
  ) +
  coord_sf(expand = FALSE) +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom"
  ))

# ggsave(
#   "./figures/rts_no_thermokarst.jpg",
#   rts_no_tk,
#   height = 7,
#   width = 6.5
# )
```

```{r}
arts_tk = arts_tk |>
  mutate(
    across(
      TKWP:TKHP,
      ~ factor(
        .x,
        levels = c("None", "Low", "Moderate", "High", "Very High"),
        ordered = TRUE
      )
    )
  ) |>
  rowwise() |>
  mutate(
    AnyTK = max(c(TKWP, TKThLP, TKHP), na.rm = TRUE)
  ) |>
  ungroup()
```

```{r}
ggplot(arts_tk) +
  geom_histogram(
    aes(x = TKHP, color = TKWP, fill = TKWP),
    stat = "count"
  ) +
  scale_color_viridis(
    name = "Wetland Thermokarst\nLikelihood\n (Olefeldt et al. 2016)",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_fill_viridis(
    name = "Wetland Thermokarst\nLikelihood\n (Olefeldt et al. 2016)",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_x_discrete(
    name = "Hillslope Thermokarst Likelihood\n(Olefeldt et al. 2016)"
  ) +
  scale_y_continuous(
    name = "Count",
    expand = expansion(mult = c(0, 0.05))
  )
```

```{r}
ggplot(arts_tk) +
  geom_histogram(
    aes(x = TKHP, color = TKThLP, fill = TKThLP),
    stat = "count"
  ) +
  scale_color_viridis(
    name = "Thermokarst Lake\nLikelihood\n (Olefeldt et al. 2016)",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_fill_viridis(
    name = "Thermokarst Lake\nLikelihood\n (Olefeldt et al. 2016)",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_x_discrete(
    name = "Hillslope Thermokarst Likelihood\n(Olefeldt et al. 2016)"
  ) +
  scale_y_continuous(
    name = "Count",
    expand = expansion(mult = c(0, 0.05))
  )
```

```{r}
(rts_tk = ggplot(arts_tk) +
  geom_histogram(
    aes(x = AnyTK, color = TKHP, fill = TKHP),
    stat = "count"
  ) +
  scale_color_viridis(
    name = "Hillslope\nThermokarst\nLikelihood",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_fill_viridis(
    name = "Hillslope\nThermokarst\nLikelihood",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_x_discrete(
    name = "Any Thermokarst Likelihood\n(Olefeldt et al. 2016)"
  ) +
  scale_y_continuous(
    name = "Count",
    expand = expansion(mult = c(0, 0.05))
  ))

# ggsave(
#   "./figures/rts_thermokarst.jpg",
#   rts_tk,
#   height = 4,
#   width = 6.5
# )
```

# Percent Cover by Thermokarst Landscapes

```{r}
arts_tk_percent_by_class = arts_tk |>
  st_drop_geometry() |>
  summarise(
    area_rts = sum(Area) / 1e6, # convert to km^2
    .by = c(TKWP, TKThLP, TKHP, area_tk)
  ) |>
  mutate(
    rts_percent = area_rts / area_tk * 100 # convert to percent
  )

arts_tk_percent = arts_tk |>
  st_drop_geometry() |>
  summarise(
    area_rts = sum(Area) / 1e6, # convert to km^2
    area_tk = sum(area_tk),
    .by = c(AnyTK)
  ) |>
  mutate(
    rts_percent = area_rts / area_tk * 100 # convert to percent
  )
```

```{r}
(rts_percent_any_tk = ggplot(arts_tk_percent) +
  geom_col(
    aes(x = AnyTK, y = rts_percent, color = AnyTK, fill = AnyTK),
    position = "dodge",
    linewidth = 1
  ) +
  scale_color_viridis(
    name = "Any Thermokarst\nLikelihood",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_fill_viridis(
    name = "Any Thermokarst\nLikelihood",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_x_discrete(
    name = "Any Thermokarst Likelihood\n(Olefeldt et al. 2016)"
  ) +
  scale_y_continuous(
    name = "RTS Percent Cover (%)",
    expand = expansion(mult = c(0, 0.05))
  ) +
  ggtitle(
    "RTS Percent Cover\nby Total Thermokarst Likelihood\n(Non-Exhaustive Inventory of RTS from ARTS)"
  ))

# ggsave(
#   "./figures/rts_percent_thermokarst.jpg",
#   rts_percent_any_tk,
#   height = 4,
#   width = 6.5
# )
```

```{r}
(rts_percent_hillslope = ggplot(arts_tk_percent_by_class) +
  geom_col(
    aes(x = TKHP, y = rts_percent, color = TKHP, fill = TKHP),
    position = "dodge",
    linewidth = 1,
    show.legend = TRUE
  ) +
  scale_color_viridis(
    name = "Hillslope\nThermokarst\nLikelihood",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_fill_viridis(
    name = "Hillslope\nThermokarst\nLikelihood",
    drop = FALSE,
    discrete = TRUE,
    na.value = "gray50"
  ) +
  scale_x_discrete(
    name = "Hillslope Thermokarst Likelihood\n(Olefeldt et al. 2016)"
  ) +
  scale_y_continuous(
    name = "RTS Percent Cover (%)",
    expand = expansion(mult = c(0, 0.05))
  ) +
  ggtitle(
    "RTS Percent Cover\nby Hillslope Thermokarst Likelihood\n(Non-Exhaustive Inventory of RTS from ARTS)"
  ))

# ggsave(
#   "./figures/rts_percent_hillslope.jpg",
#   rts_percent_hillslope,
#   height = 4,
#   width = 6.5
# )
```

# Multiple RTS in DVM-DOS-TEM Grid Cells

```{r}
arts_filter_6931 = arts_filter |>
  st_transform(crs = 6931)
```

```{r}
rts_counts = tem_grid |>
  mutate(
    grid_area = as.numeric(st_area(tem_grid)) / 1e6, # convert to km^2
    rts_count = lengths(st_intersects(tem_grid, arts_filter_6931)),
    rts_density = rts_count / grid_area
  )
```

```{r}
(rts_density = ggplot(
  rts_counts |>
    filter(rts_density != 0),
  aes(x = rts_density)
) +
  geom_histogram(
    aes(y = ..count.. / sum(..count..)),
    color = "gray35",
    linewidth = 1,
    binwidth = 1,
    boundary = 0
  ) +
  scale_x_continuous(
    name = expression("RTS Density (# km"^-2 ~ ")")
  ) +
  scale_y_continuous(
    name = "Proportion",
    expand = expansion(mult = c(0, 0.05))
  ) +
  ggtitle("RTS Density\n(Excluding Density == 0)"))

# ggsave(
#   "./figures/rts_density.jpg",
#   rts_density,
#   height = 3,
#   width = 4
# )
```

```{r}
(density_hist = ggplot(
  rts_counts,
  aes(x = rts_density)
) +
  geom_histogram(
    aes(y = ..count.. / sum(..count..)),
    color = "gray35",
    linewidth = 1,
    binwidth = 1,
    center = 0
  ) +
  scale_x_continuous(
    name = expression("RTS Density (# km"^-2 ~ ")")
  ) +
  scale_y_continuous(
    name = "Proportion\n(sqrt transformation)",
    expand = expansion(mult = c(0, 0.05)),
    transform = "sqrt",
    breaks = c(0, 0.001, 0.01, 0.1, 1),
    minor_breaks = NULL
  ) +
  ggtitle("RTS Density\n(Incl. 0; Sqrt Transformation)"))

# ggsave(
#   "./figures/rts_density_ysqrt.jpg",
#   density_hist,
#   height = 3,
#   width = 4
# )

density_bin_data = ggplot_build(density_hist)$data[[1]]
density_bin_data = density_bin_data |>
  select(density_min = xmin, density_max = xmax, count)
# write_csv(
#   density_bin_data,
#   "./data/density_bin_data.csv"
# )
```

```{r}
(density_hist = ggplot(
  rts_counts |> filter(rts_count != 0),
  aes(x = rts_count)
) +
  geom_histogram(
    aes(y = ..count.. / sum(..count..)),
    color = "gray35",
    linewidth = 1,
    binwidth = 1,
    center = 0,
    closed = "left"
  ) +
  scale_x_continuous(
    name = expression("RTS Density (# TEMgridcell"^-1 ~ ")")
  ) +
  scale_y_continuous(
    name = "Proportion of TEM Grid Cells",
    expand = expansion(mult = c(0, 0.05)),
    minor_breaks = NULL
  ) +
  ggtitle("RTS Count per TEM Grid Cell\n(Excluding Count == 0)"))

# ggsave(
#   "./figures/rts_count_per_tem_gridcell.jpg",
#   density_hist,
#   height = 3,
#   width = 4
# )
```

```{r}
bbox = st_bbox(
  rts_counts |>
    filter(rts_density != 0)
)

ggplot() +
  geom_sf(data = world) +
  geom_sf(
    data = rts_counts |>
      filter(rts_density != 0),
    aes(color = rts_density, fill = rts_density),
    linewidth = 1
  ) +
  scale_color_viridis(trans = "log10") +
  scale_fill_viridis(trans = "log10") +
  coord_sf(
    expand = FALSE,
    xlim = c(bbox["xmin"], bbox["xmax"]),
    ylim = c(bbox["ymin"], bbox["ymax"])
  )

# ggsave(
#   "./figures/rts_density_map.jpg",
#   height = 5,
#   width = 6.5
# )
```